encadeada:
	# Compilando a implementacao da fila
	gcc -c pilha_encadeada.c -o pilha_encadeada.o
	
	# Compilando e gerando o executavel
	gcc main.c pilha_encadeada.o -o main
	
	# Executando
	./main

clean:
	rm *.o
	rm main